apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: educated-guess-backend
spec:
  type: ClusterIP
  selector:
    app: educated-guess-backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    name: http
