apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: educated-guess-frontend
spec:
  type: ClusterIP
  selector:
    app: educated-guess-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
